name: Update GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake SVG
        run: |
          curl -o github-contribution-grid-snake.svg https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake.svg

      - name: Commit and Push updated snake SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "chore: update GitHub contribution snake graph [skip ci]" || echo "No changes to commit"
          git push
